//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.13 at 04:35:08 PM EET 
//


package cert.cert.xsd;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cert.cert.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TransfDataInRequest_QNAME = new QName("", "transfDataInRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cert.cert.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TransfDataInRequestType }
     * 
     */
    public TransfDataInRequestType createTransfDataInRequestType() {
        return new TransfDataInRequestType();
    }

    /**
     * Create an instance of {@link TransfDataInInfoType }
     * 
     */
    public TransfDataInInfoType createTransfDataInInfoType() {
        return new TransfDataInInfoType();
    }

    /**
     * Create an instance of {@link DocType }
     * 
     */
    public DocType createDocType() {
        return new DocType();
    }

    /**
     * Create an instance of {@link TransfDataListType }
     * 
     */
    public TransfDataListType createTransfDataListType() {
        return new TransfDataListType();
    }

    /**
     * Create an instance of {@link TransferenceDataType }
     * 
     */
    public TransferenceDataType createTransferenceDataType() {
        return new TransferenceDataType();
    }

    /**
     * Create an instance of {@link AddrType }
     * 
     */
    public AddrType createAddrType() {
        return new AddrType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransfDataInRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "transfDataInRequest")
    public JAXBElement<TransfDataInRequestType> createTransfDataInRequest(TransfDataInRequestType value) {
        return new JAXBElement<TransfDataInRequestType>(_TransfDataInRequest_QNAME, TransfDataInRequestType.class, null, value);
    }

}
