//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.13 at 04:35:08 PM EET 
//


package cert.cert.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for transfDataInRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="transfDataInRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="info" type="{}transfDataInInfoType"/>
 *         &lt;element name="transfDataList" type="{}transfDataListType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "transfDataInRequestType", propOrder = {
    "info",
    "transfDataList"
})
public class TransfDataInRequestType {

    @XmlElement(required = true)
    protected TransfDataInInfoType info;
    @XmlElement(required = true)
    protected TransfDataListType transfDataList;

    /**
     * Gets the value of the info property.
     * 
     * @return
     *     possible object is
     *     {@link TransfDataInInfoType }
     *     
     */
    public TransfDataInInfoType getInfo() {
        return info;
    }

    /**
     * Sets the value of the info property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransfDataInInfoType }
     *     
     */
    public void setInfo(TransfDataInInfoType value) {
        this.info = value;
    }

    /**
     * Gets the value of the transfDataList property.
     * 
     * @return
     *     possible object is
     *     {@link TransfDataListType }
     *     
     */
    public TransfDataListType getTransfDataList() {
        return transfDataList;
    }

    /**
     * Sets the value of the transfDataList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransfDataListType }
     *     
     */
    public void setTransfDataList(TransfDataListType value) {
        this.transfDataList = value;
    }

}
